services:
  - postgresql
addons:
  postgresql: "9.4"
rvm:
  - 2.4.2
sudo: required
env:
  - DB=postgresql
before_install:
  - gem update --system
  - gem --version
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
