# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ea4d9fd550ec88cab07da0fa271bdbdd08f7da5bc9657c491dd01bb24ba73a20c632c46e3df455ecaa3047fae05486d1bc4700a86658f264118e0e4e77fbc8f

test:
  secret_key_base: 3e12f9610c030fe202bf2026a6d53f7723b982d378fcb785e70cee411ab3d691e6b495c7312795d70d7b8df641c06ce3ae60db1af7da8bb2fa2549b71bf71ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
