content:
  readmore_tag: "<<READMORE>>"
  show_number_on_index: 10
site_owner:
  email: "raviwu@gmail.com"
  github_profile: "https://github.com/raviwu"
  linkedin_profile: "https://tw.linkedin.com/in/raviwu"
