site_owner:
  site_name: "LW Studio"
  ebook_intro: "自從接觸奧地利學派後，深受其吸引，也感念於 [Mises Institute](https://mises.org/) 在網路上提供大量方便取閱的書籍專著，開啟另一片知性的天地。\n\n為了推廣這些我所認同的信念，我也在 2012 年開始寫起 LW Studio 這個網站，雖然至今讀者仍然很少，但仍覺得自己的為文內容，強度不足以完整表達理論的全貌。\n\n也因此，突然決定開始系統性地翻譯一些 [Mises Institute](https://mises.org/) 上所提供的專著，將值得一看的內容逐步中文化，也充當自己業餘時間的娛樂。\n\n所完成的譯文，將以電子書的形式發布，早期譯作皆為個人獨自排版完成的 epub、mobi 與 pdf，譯文沒有太多心力校對很多次，但排版設計總盡量做到精美與清晰。\n\n由於個人的工作變動，可用來翻譯的時間大幅萎縮，為了節省排版的時間以維持翻譯產量，未來的譯作將透過 [Leanpub](https://leanpub.com/u/raviwu) 的服務發布，當然，還是都能夠免費取得、自由散播。\n\n所有本站所提供的原創內容，不管是文章或是書籍翻譯，都採用[創用 CC 姓名標示授權](http://creativecommons.org/licenses/by/3.0/deed.zh_TW)，換句話說，只需標明內容出處即可自由改作、引用或運用至商業用途。"
  footer:
    left_column:
      icon: "copyright"
      title: "版權說明"
      content: "陸續發表之電子書以及簡報，可於 [Leanpub](https://leanpub.com/u/raviwu) 平台或本站自由電子書網頁上購得或免費下載。\n\nLW Studio 網站內容由吳莉瑋製作，以 [創用 CC 姓名標示授權](http://creativecommons.org/licenses/by/3.0/deed.zh_TW) 釋出，如果派得上任何用場，只要尊重姓名表示權，歡迎取用。"
    right_column:
      icon: "support"
      title: "支持 LW Studio"
      content: "LW Studio 的網站內容需要花上許多時間製作與準備，這些工作都需要經費，除了透過 Leanpub 購買電子書外，您還能透過 Bitcoin 直接支持 LW Studio：`1E5RntcxdqguuAd6Pfpj96NWNgUJbRnYVe`"
    bottom_line: "Ravi L.W. Wu &copy; 2013-2016"
